/* oxlint-disable next/no-html-link-for-pages -- Use full document navigation for reliable case links on the hosted portfolio. */

import {BodyImage} from '@/app/components/body-visuals';
import type { Metadata } from 'next';
import { CaseOverview, ProductView, EvidencePanel } from '@/app/components/case-overview';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
export const metadata: Metadata = {title:'Project Knowledge Copilot · 王誉翔的 AI 产品案例',description:'建筑团队知识助手：从可追溯 RAG 到检索策略实验、真实资料评估与原文阅读。'};
const repo='https://github.com/wyuxiang020-ctrl/Project-Knowledge-Copilot';
const nav=[['problem','问题与洞察'],['experience','核心体验'],['decisions','产品决策'],['architecture','系统设计'],['evaluation','评估证据'],['reflection','复盘与边界']];
function Results({headers,rows}:{headers:string[];rows:string[][]}){return <div className="results-table"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
export default function KnowledgeCase(){return <div id="top" className="knowledge-page"><a className="skip" href="#overview">跳到案例概览</a><header className="wrap header"><a className="brand" href="/">Y<span>／</span><small>YUXIANG WANG</small></a><nav aria-label="案例导航"><a href="/#projects">← 全部作品</a><a href={repo} target="_blank" rel="noreferrer">查看源码 ↗</a></nav></header><main>
<section className="wrap case-hero"><div className="case-heading"><p className="eyebrow">AI PRODUCT CASE STUDY / 01</p><p className="case-product-name">PROJECT KNOWLEDGE COPILOT</p><h1>从历史资料中找答案，<br/><strong>让每个判断有据可查。</strong></h1><div className="case-actions"><a className="primary" href="#overview">一分钟了解案例 <span>↓</span></a><a className="text-action" href={repo} target="_blank" rel="noreferrer">查看源码 ↗</a></div></div><div className="case-summary"><p className="case-lead">面向建筑与设计团队的 AI 知识助手。用自然语言查找、比较历史项目，并从回答中的引用回到原始资料，核验每个判断的依据。</p><div className="case-tags"><span>RAG</span><span>产品决策</span><span>Evaluation</span><span>可追溯体验</span><span>可运行 MVP</span></div><p className="availability">应用目前为本地 Demo，公开在线体验与演示视频尚未提供。</p></div><div className="case-facts"><div><span>我的角色</span><p>产品定义 · 架构判断 · 评估与验收</p></div><div><span>项目时间</span><p>2026.05 — 2026.08<br/>后续持续迭代</p></div><div><span>实现方式</span><p>本人主导 · AI 辅助开发</p></div><div><span>问题来源</span><p>建筑与设计背景 · 真实项目资料</p></div></div></section>
<CaseOverview project="knowledge"/><ProductView project="knowledge"/><section className="full-case" id="full-case"><div className="wrap narrative-heading"><p className="eyebrow">产品推导 / CASE STUDY</p><h2>从问题到选择，<strong>再到验证。</strong></h2></div><div className="wrap case-layout"><aside className="case-sidebar"><p className="eyebrow">案例章节</p><nav aria-label="章节导航">{nav.map(([id,label],i)=><a key={id} href={'#'+id}><span>0{i+1}</span>{label}</a>)}</nav><a href="/#projects" className="back">← 返回作品集</a></aside><div className="case-content">
<section id="problem" className="story-section"><p className="eyebrow">01 / THE PROBLEM</p><h2>资料不断积累，<br/><span>知识却很难复用。</span></h2><p>新方案需要参考案例，投标需要核对材料与空间策略，新成员需要理解项目历史。答案可能已经存在，却分散在设计说明、技术总结和长篇 PDF 中。查找往往依赖文件名、个人记忆，以及熟悉项目的同事。</p><div className="insight"><span>CORE INSIGHT</span><h3>找到一段文字，只完成了一半任务。</h3><p>用户还需要确认它来自哪里、是否适用于当前判断。产品必须把“发现资料”和“核验依据”连成一条完整路径。</p></div><p className="method-note">这是基于专业背景和真实资料形成的问题假设，尚无正式访谈样本、企业试点或付费客户记录。“减少查找时间”是产品目标，尚未通过计时对照验证。</p></section>
<section id="experience" className="story-section"><p className="eyebrow">02 / THE EXPERIENCE</p><h2>找到、理解，<strong>再核验。</strong></h2><div className="experience-list">{[['01','确定搜索范围','不知道相关项目时搜索全部资料；知道目标时选择一个项目；需要比较时明确选择 2–4 个项目。'],['02','阅读受证据约束的回答','系统组织检索片段并附上引用，证据不足时说明原因；请求失败与证据不足采用不同状态。'],['03','回到原始资料','从行内引用查看来源片段与相邻上下文，进入项目资料页，阅读逻辑文档并在 PDF 阅读器中翻页、缩放与切换分卷。']].map(x=><div key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div><p className="method-note">以上为已实现流程的文字说明。案例未使用真实投标资料截图；公开视觉素材将使用独立合成数据。</p></section>
<section id="decisions" className="story-section"><p className="eyebrow">03 / PRODUCT DECISIONS</p><h2>最重要的优化，<br/><span>来自没有改善的结果。</span></h2><article className="decision"><span className="decision-label">D21 / 检索策略实验</span><h3>项目覆盖变好了，为什么仍不采用？</h3><p>全局 Top-5 可能遗漏跨项目证据。我尝试扩大到 Top-20 候选，再按项目均衡选出 5 个 chunks；Embedding、生成模型与提示词保持一致。</p><Results headers={['C1–C4 对照指标','原方案','项目均衡方案']} rows={[
['找到目标项目（共需 11 次）','9 次','11 次'],['找到有效证据（同一组 11 次需求）','6 次','6 次'],['C4 所需证据覆盖','1/3','1/3']
]}/><p className="method-note">4 道比较题合计需要覆盖 11 次目标项目，同一项目在不同题中分别计数。找到目标项目表示检索结果中出现该项目；有效证据则还需通过问题对应的确定性模式检查。</p><div className="decision-result"><b>决策：保留默认全局检索。</b><p>更多项目出现，没有带来更多问题所需的事实。后续转向让用户明确选择比较对象，再在目标项目内检索；选中项目仍不保证证据充分。</p></div></article>
<article className="decision"><span className="decision-label">D30 / 信息组织与上下文</span><h3>浏览十个项目，不必让模型读十份资料。</h3><p>用户以“项目”理解内容，系统却以 chunk 检索。直接把 Top-5 改成 Top-10，仍可能只有少数几个项目。</p><div className="split-facts"><div><b>Top-5 证据</b><p>全局回答继续使用少量具体片段，控制上下文规模。</p></div><div><b>Top-10 项目</b><p>按项目聚合结果，提供最多十张不同项目卡片。</p></div></div><p>两路检索复用同一个问题向量。项目浏览范围与回答证据量分别设计，也避免为展示卡片重复生成问题向量。</p></article>
<article className="decision"><span className="decision-label">D18 / 信任与失败体验</span><h3>“没有依据”和“请求失败”，需要不同的下一步。</h3><p>系统区分 answered、no_evidence、unverifiable 和 error，分别对应正常回答、证据不足、引用无法核验与请求错误。原始评估暴露一次结构化生成异常后，我补充了有限重试，原问题定向复测成功。</p><p className="method-note">没有完整重跑原始 16 题，因此不能把定向复测成功写成失败率降至 0%；unverifiable 的前端状态曾使用模拟响应验证。</p></article>
<article className="decision"><span className="decision-label">D29–D32 / 大文档与阅读体验</span><h3>底层分卷，不应割裂用户的阅读任务。</h3><p>真实投标 PDF 暴露存储大小与向量化限流约束。我加入入库工作量预览、可恢复批量 Embedding，并将物理分卷组织成逻辑文档，保留原始页码。搜索框前置、项目选择折叠，再用 PDF.js 完成原文阅读。</p><p>三个分卷已能呈现为一份 134 页逻辑文档，第二卷第一页对应原始第 46 页。恢复处理会跳过已有向量，减少重复调用。</p></article></section>
<BodyImage src="knowledge-architecture-hd.png" title="RAG 架构与产品取舍" caption="来自用户作品集 PDF 第 4 页，以两倍尺寸重新渲染，展示资料处理、检索、引用与验证的关系。" width={2382} height={1684}/><section id="architecture" className="story-section"><p className="eyebrow">04 / SYSTEM DESIGN</p><h2>让错误，<strong>可以被定位。</strong></h2><p>将文档处理、检索、生成和引用核验拆开检查。Voyage 负责向量化与语义查找，Claude 负责基于证据组织回答，引用编号由程序校验；编号有效仍不等于语义有依据。</p><div className="pipeline"><span>INGESTION / 入库</span><ol>{['上传 PDF / TXT / Markdown','提取文本 · 预览工作量','分块 · 保存项目、文档与页码','Voyage 批量向量化 → pgvector'].map(x=><li key={x}>{x}</li>)}</ol><p>目标分块长度 1,000 字符，重叠 150 字符；PDF 先按页切分，再在页内分块。</p></div><div className="pipeline"><span>QUERY / 查询与核验</span><ol>{['提问并选择项目范围','Voyage 生成一次问题向量','证据检索 + 项目级聚合检索','Claude 生成引用回答 / 说明证据不足','引用编号校验 → 来源上下文 → 原文阅读'].map(x=><li key={x}>{x}</li>)}</ol></div><p className="stack-line">Next.js · TypeScript · Supabase Postgres / 私有 Storage · pgvector · Voyage AI · Claude API · pdf-parse · PDF.js</p><p className="method-note">PDF 阅读能力与模型理解能力分开：当前主要依赖文本提取，不包含 OCR 或图纸视觉检索。</p></section>
<section id="evaluation" className="story-section"><p className="eyebrow">05 / EVIDENCE & EVALUATION</p><h2>保留分母，<strong>也保留失败。</strong></h2><p>不同阶段使用不同数据与检查方式，以下分别呈现，避免混成一个“系统准确率”。结果摘自项目评估记录，本次网站整理没有重新调用模型评测。</p><h3>Phase 8 · 小规模真实资料基线</h3><p>3 个真实个人建筑项目、6 份文档、19 个 chunks；16 题包括 8 个已知答案、4 个跨项目比较和 4 个未知答案。</p><Results headers={['检查项','结果','分母与方法']} rows={[
['Retrieval Hit@1','7/8 · 87.5%','8 个已知答案问题'],['Retrieval Hit@3','8/8','正确证据位于前三名'],['相关性、依据与引用支持','10/10','仅成功回答；由作者检查'],['应拒答案例','5/5','4 个未知 + 1 个证据不完整的比较'],['原始生成失败','1/16','保留原始失败，后续仅定向复测'],['成功请求延迟中位数','约 6.7 秒','该小规模测试中的观察值']
]}/><p className="method-note">小样本、自评且存在生成失败，不能解释为“系统准确率 100%”或普遍的零幻觉保证。</p>
<h3>Phase 10 · 大型真实投标 PDF</h3><div className="mini-evidence"><span><b>293 页</b>2 份原始 PDF · 5 份私有分卷</span><span><b>289/289</b>chunks 完成 Embedding</span></div><p>入库提取 37,964 字符。7 次文档 Embedding 请求成功，另有 1 次限流失败。一个比较问题在全局检索中仅覆盖 1/2 目标项目，显式选择后覆盖 2/2；两个未知问题均正确返回 no_evidence。</p><p>包含定向复测的 6 次成功回答，引用编号有效，并通过 Claude 辅助语义审查。原始运行有 2 个问题在有限重试后仍生成失败，其中 1 个复测成功、另 1 个仍失败。</p><div className="insight"><span>REMAINING PRODUCT PROBLEM</span><h3>成功路径约 14.2 秒，失败复测约 200.6 秒。</h3><p>前者是六次成功回答的延迟中位数，后者是一次失败问题的定向复测耗时。失败路径的等待体验仍需优先改进。模型辅助审查不等同于独立人工认证。</p></div>
<h3>合成 Demo · 数据准备完成，质量评测待完成</h3><p>独立环境包含 12 个虚构项目、24 份文档、48 个 chunks，全部完成向量化；24/24 原始文件与生成源一致。先定义事实清单，再确定性生成文档，最后校验与入库。</p><p className="method-note">独立测试集包含 24 题，但尚无整套质量评测完成记录。真实资料基线指标不能移用到合成 Demo。</p>
<h3>Phase 11 · 功能回归</h3><p>真实环境返回 6 张不同项目卡片，合成环境能返回 10 张；完成逻辑文档分组、翻页与分卷切换验证。容量检查复用已有向量，无额外模型调用。</p><p className="method-note">十张卡片属于容量验证，不代表项目召回率 100%；目前没有项目级相关性标注集。</p><a className="text-action" href={repo} target="_blank" rel="noreferrer">在源码仓库查看产品与评估文档 ↗</a></section>
<section id="reflection" className="story-section"><p className="eyebrow">06 / REFLECTION</p><h2>交付一个 MVP，<br/><span>也明确它的边界。</span></h2><p>我主导行业问题定义、MVP 范围、架构判断、评估设计与交付验收。Phase 1–8 主要由 Claude Code 协助实现，后续由 Codex 接手开发协作；产品判断通过决策记录与实验结果保留。</p><div className="split-facts"><div><h3>当前局限</h3><ul><li>没有 OCR 或图纸视觉理解，短标签和上下文不足的片段检索较弱。</li><li>有限重试仍会失败；入库需分步触发，分卷元数据主要手动维护。</li><li>真实资料实例未配置登录与资源授权，保持本地使用。</li><li>尚无企业采用、持续使用或节省工时的数据。</li></ul></div><div><h3>下一步验证</h3><ol><li>完成合成 Demo 的独立 24 题评估。</li><li>用合成资料制作截图、视频与 PDF 阅读演示。</li><li>开展文件夹搜索与本产品的任务计时对照。</li><li>公开交互前完善访问控制、写入限制与调用成本控制。</li></ol></div></div><div className="closing"><p>这次实践让我更关注：用户是否拿到了所需证据，以及下一步能否核验和使用它。</p><a className="text-action" href="/#projects">← 返回全部作品</a><a className="text-action" href="mailto:m17347819733@163.com">与我交流 ↗</a></div></section>
</div></div></section><EvidencePanel project="knowledge"/><div className="wrap case-next"><a href="/#projects">← 返回全部作品</a><a href="/resume/">查看简历 ↗</a><a href="mailto:m17347819733@163.com">邮件交流 ↗</a></div></main><footer className="wrap footer"><span>© 2026 王誉翔 · Yuxiang Wang</span><span>Project Knowledge Copilot</span><a href="#top">回到顶部 ↑</a></footer></div>}


