/* oxlint-disable next/no-img-element -- Preserve original evidence images, with explicit dimensions and lazy loading. */
/* oxlint-disable next/no-html-link-for-pages -- Native document links are intentional. */
import evidence from '@/app/data/evidence.json';
import ProjectGallery from './project-gallery';

const data = {
 gym: {problem:'训练中重复填写计划里已有的信息，补录时又容易把猜测写成事实。',choice:'常规记录优先复用计划；AI 只生成可编辑草稿，用户确认后写入。',result:'20 条合成解析回归：边界 6/8 → 8/8；延迟中位数 5.29 → 6.41 秒。',limit:'个人场景与合成 API 测试；尚无真人编辑率、节省时间或留存证据。',decision:'#strategy'},
 knowledge: {problem:'建筑资料分散；找到相关项目后，仍需判断回答是否有原文支持。',choice:'把检索与生成分开评估。项目均衡策略未补齐有效证据，因此不设为默认。',result:'Phase 9 的 4 道比较题共需覆盖 11 次目标项目：检索找到的目标从 9 次增至 11 次，但找到有效证据的仍只有 6 次。',limit:'小样本真实资料测试；指标为特定评测范围，不代表企业采用或业务效果。',decision:'#decisions'},
 spatial: {problem:'长 PDF 和大型专业模型，使访客难以快速理解设计并深入查看空间。',choice:'内容分层阅读；高清图纸与真实 3D 按需打开，退出后保留阅读位置。',result:'11 个页面、两个模型已交付；9 月 7 日部署记录确认生产发布。',limit:'AI 用于开发协作；尚无访客端 AI、真实用户任务测试或完整真机验证。',decision:'#decisions'}
};
export function CaseOverview({project}:{project:keyof typeof data}){
 const d=data[project];
 return <section className="wrap case-overview" id="overview" aria-label="案例快速概览"><div className="overview-heading"><p className="eyebrow">一分钟概览 / AT A GLANCE</p><a href="#evidence" className="text-action">直接查看证据 ↓</a></div><div className="overview-grid">{[['用户问题',d.problem],['我的关键选择',d.choice],['已有结果',d.result],['证据边界',d.limit]].map(([title,text])=><div key={title}><h2>{title}</h2><p>{text}</p></div>)}</div><div className="reading-path"><a href="#product-view">01 看产品 ↓</a><a href={d.decision}>02 读决策 ↓</a><a href="#evidence">03 核对证据 ↓</a><a href="#full-case">阅读完整复盘 ↓</a></div></section>
}
export function ProductView({project}:{project:keyof typeof data}){
 return <section className="wrap product-view" id="product-view"><p className="eyebrow">产品与关键取舍 / PRODUCT IN CONTEXT</p>
 <ProjectGallery project={project}/>{project==='gym'?<><h2>先复用计划，<strong>再核对事实。</strong></h2><p className="view-intro">以下来自现有 Gym 界面，均为合成演示数据，不代表真人健康记录。点击图片可查看原尺寸。</p><div className="screen-sequence">{[['gym-confirm.png','核对 AI 草稿','未知重量保留提示，用户可编辑后确认。']].map(([src,title,desc])=><figure key={src}><a href={'/media/'+src} data-lightbox><img src={'/media/'+src} width="415" height="899" loading="lazy" alt={title+'：'+desc}/></a><figcaption><b>{title}</b><span>{desc}</span></figcaption></figure>)}<div className="visual-takeaway"><span className="eyebrow">为什么保留人工确认</span><h3>模型提供候选，<br/>用户决定事实。</h3><p>“重量忘了”仍应保留已知组次。当前 0kg 同时承担自重和缺失占位，提示可以被忽略，仍是待解决的交互问题。</p><a className="text-action" href="#architecture">阅读数据合约与边界 ↓</a></div></div></>:project==='knowledge'?<><h2>相关，不等于<strong>有证据。</strong></h2><p className="view-intro">产品链路示意 · 根据已实现流程整理，非界面截图或在线 Demo。</p><ol className="task-flow">{[['限定项目提问','自然语言搜索，必要时选择项目范围'],['检索原文片段','回答使用 Top 5 证据，与项目卡片分开'],['生成带引用回答','不足时拒答；异常不冒充正常结果'],['回到原始 PDF','从引用核验来源，再判断是否可复用']].map(([title,desc],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></li>)}</ol><div className="decision-comparison"><div><span>实验改变了什么</span><h3>找到目标项目的次数</h3><b>9/11 → 11/11</b></div><div><span>用户需要的证据呢？</span><h3>找到有效证据的次数</h3><b>6/11 → 6/11</b></div><p>结论：不将项目均衡策略设为默认。分母 11 是 4 道比较题（C1–C4）所需的目标项目次数之和，同一项目在不同题中重复计数，不是 11 道题或 11 个不同项目；有效证据使用确定性模式检查，并非逐句人工认证。</p></div></>:<><h2>从图纸理解，<strong>到空间探索。</strong></h2><p className="view-intro">真实建筑资料节选。图像展示内容组织，交互模型请进入已发布建筑网站体验。</p><div className="spatial-preview"><a href="/media/spatial-structure.jpg" data-lightbox><img src="/media/spatial-structure.jpg" width="2263" height="3200" loading="lazy" alt="祖母的火塘建筑结构分解轴测图：屋顶、梁架、围护与院落的空间关系"/></a><div><p className="eyebrow">祖母的火塘 / GRANDMOTHER’S HEARTH</p><h3>先看清层次，<br/>再自主选择视角。</h3><p>网页先呈现设计主线与图纸。需要理解三维关系时，再主动加载模型，减少默认阅读的资源负担。</p><a className="primary" href="https://portfolio-nine-alpha-vjzzxk79fm.vercel.app/work/grandmothers-hearth/#interactive-model" target="_blank" rel="noreferrer">进入火塘 3D 体验 ↗</a><a className="text-action" href="https://portfolio-nine-alpha-vjzzxk79fm.vercel.app/work/iterative-learning/#interactive-model" target="_blank" rel="noreferrer">查看 ITB 交互模型 ↗</a><p className="method-note">模型约 22.7 MiB / 6.2 MiB，进入后点击加载。原建筑作品含 Yuxiang Wang、Han Liu 合作署名；本案例评价网站开发与交互取舍。</p></div></div></>}
 </section>
}
export function EvidencePanel({project}:{project:keyof typeof data}){
 const items=evidence.filter(item=>item.project===project);
 return <section className="wrap evidence-panel" id="evidence"><div className="overview-heading"><div><p className="eyebrow">证据入口 / EVIDENCE</p><h2>结论可以<strong>回到记录。</strong></h2></div></div><p className="view-intro">以下为已有项目记录的归档或节选。本轮核对文件与结论，未重新运行模型评测；原始运行、定向复测和用户验证分别说明。</p>{project==='gym'&&<p><a className="text-action" href="/evidence/gym-photo-estimates.json" download>下载照片营养估算 · FP-01–FP-04 数据节选 ↓</a></p>}<div className="evidence-list">{items.map(item=><article key={item.file}><span className="evidence-type">{item.type}</span><h3>{item.title}</h3><p>{item.note}</p><details><summary>阅读记录{item.excerpt?'节选':''}</summary><pre>{item.content}</pre></details><a className="text-action" href={'/evidence/'+item.file} download>下载记录 · Markdown ↓</a></article>)}</div><p className="method-note">归档日期：2026.09.07。下载文件附来源位置与 SHA-256，便于比对；哈希说明文件对应关系，不构成独立验证。</p></section>
}
