import {SpatialShowcase} from '@/app/components/case-showcase';
/* oxlint-disable next/no-html-link-for-pages -- Full document navigation keeps hosted portfolio links reliable. */
import type { Metadata } from 'next';
import { CaseOverview, EvidencePanel } from '@/app/components/case-overview';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
export const metadata: Metadata = {title:'建筑作品集与交互式 3D · 王誉翔的产品实践',description:'AI 辅助开发实践：从 PDF 到分层阅读、高清图纸与真实 3D 探索，记录内容、性能和交互取舍。'};
const repo='https://github.com/wyuxiang020-ctrl/portfolio';
const nav=[['problem','问题与目标'],['experience','产品体验'],['decisions','关键取舍'],['delivery','实现与协作'],['evaluation','验证证据'],['reflection','边界与下一步']];
function Results({headers,rows}:{headers:string[];rows:string[][]}){return <div className="results-table"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
export default function SpatialPortfolio(){return <div id="top" className="knowledge-page revised-case spatial-case"><a className="skip" href="#overview">跳到案例概览</a><header className="wrap header"><a className="brand" href="/">Y<span>／</span><small>YUXIANG WANG</small></a><nav aria-label="案例导航"><a href="/#projects">← 全部作品</a><a href={repo} target="_blank" rel="noreferrer">查看源码 ↗</a></nav></header><main>
<section className="wrap case-hero"><div className="case-heading"><p className="eyebrow">AI-ASSISTED PRODUCT DEVELOPMENT / 03</p><p className="case-product-name">ARCHITECTURE PORTFOLIO & INTERACTIVE 3D</p><h1>把建筑作品，<br/><strong>变成可以探索的空间。</strong></h1><div className="case-actions"><a className="primary" href="#overview">一分钟了解案例 <span>↓</span></a><a className="text-action" href={repo} target="_blank" rel="noreferrer">查看源码 ↗</a></div></div><div className="case-summary"><p className="case-lead">以真实建筑资料为基础，将 PDF 展示转化为支持分层阅读、高清图纸查看和真实 3D 探索的网站。我负责目标、需求优先级、内容方向与验收要求，借助 Claude Code 和 Codex 持续迭代。</p><div className="case-tags"><span>信息架构</span><span>交互式 3D</span><span>资源成本</span><span>AI 辅助开发</span><span>访客端 AI 待接入</span></div><p className="availability">SHIPPED · 2026.09 已有生产发布记录。AI 用于开发协作；真实用户与多网络体验仍待验证。</p></div><div className="case-facts"><div><span>我的角色</span><p>需求与优先级 · 内容方向 · 验收</p></div><div><span>项目时间</span><p>2026.04 — 至今</p></div><div><span>当前范围</span><p>11 个静态页面 · 7 个建筑项目</p></div><div><span>AI 的职责</span><p>开发协作，尚非访客功能</p></div></div></section>
<SpatialShowcase/><CaseOverview project="spatial"/><section className="full-case" id="full-case"><div className="wrap narrative-heading"><p className="eyebrow">产品推导 / CASE STUDY</p><h2>从问题到选择，<strong>再到验证。</strong></h2></div><div className="wrap case-layout"><aside className="case-sidebar"><p className="eyebrow">ON THIS PAGE / 本页</p><nav aria-label="章节导航">{nav.map(([id,label],i)=><a key={id} href={'#'+id}><span>0{i+1}</span>{label}</a>)}</nav><a className="back" href="/#projects">← 返回作品集</a></aside><div className="case-content"><section id="problem" className="story-section"><p className="eyebrow">01 / THE PROBLEM</p><h2>材料很完整，<br/><span>阅读路径却不够清晰。</span></h2><p>已有资料涵盖调研、概念分析、平剖面、效果图、实体模型与专业建模文件。长 PDF 要求读者逐页阅读，不同版本还有重复内容；二维图像限定观看视角，大型模型又依赖专业软件。</p><p>随着制作推进，需求从视觉效果扩展到真实操作：图纸能否看清，关闭大图能否回到原位置，页面返回后模型是否仍然稳定，加载失败后能否继续阅读。</p><div className="insight"><span>PRODUCT GOAL</span><h3>先理解项目，再按需要深入。</h3><p>让读者快速建立概览，再自主查看设计依据、高清图纸与三维空间；控制默认加载成本，并减少操作对阅读的打断。</p></div><p className="method-note">招聘者、设计评审、合作者与非专业访客是后续验证的目标人群，目前没有独立访谈或真实用户任务测试支撑已验证的用户画像。</p></section>
<section id="experience" className="story-section"><p className="eyebrow">02 / THE EXPERIENCE</p><h2>把阅读深度，<strong>交给访客。</strong></h2><div className="experience-list">{[['01','沿主线理解设计','概览、场地与原建筑、概念推演、图纸、实体模型逐层展开；独有研究放入补充内容，避免重复材料占据主线。'],['02','需要细节时查看高清图纸','正文使用响应式展示图；点击查看原图，支持缩放、图库切换与键盘操作。Banner 可独立查看，关闭后恢复焦点与阅读位置。'],['03','最后进入真实 3D 探索','查看器放在正文末尾，点击后才加载。通过旋转、缩放、平移、预设视角和显示控制探索空间，也可关闭模型继续阅读。']].map(x=><div key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div><div className="model-entry-links"><a className="primary" href="https://portfolio-nine-alpha-vjzzxk79fm.vercel.app/work/grandmothers-hearth/#interactive-model" target="_blank" rel="noreferrer">打开火塘模型 ↗</a><a className="text-action" href="https://portfolio-nine-alpha-vjzzxk79fm.vercel.app/work/iterative-learning/#interactive-model" target="_blank" rel="noreferrer">打开 ITB 模型 ↗</a></div><h3>两个真实模型，采用不同的信息组织</h3><Results headers={['已实现能力','ITB 迭代学习','祖母的火塘']} rows={[
['模型来源','Rhino','SketchUp'],['网页模型体积','约 6.2 MiB','约 22.7 MiB'],['预设视角','总览、俯视、正面、侧面','四种基础视角 + 完整场地'],['显示控制','23 个原命名图层','建筑与院落 / 场地与道路'],['共同操作','旋转、缩放、平移、重置、关闭','旋转、缩放、平移、重置、关闭'],['加载与异常','点击加载、进度、超时与重试','复用相同机制']
]}/><p className="method-note">当前没有改造前后切换，也没有经作者确认的入口、保留结构等语义控制。图层开关不等于模型已理解空间语义。</p></section>
<section id="decisions" className="story-section"><p className="eyebrow">03 / PRODUCT DECISIONS</p><h2>让展示方式，<br/><span>服务于理解。</span></h2><article className="decision"><span className="decision-label">01 / 内容主线与补充阅读</span><h3>整合 180 页资料，不把全部内容平铺上网。</h3><p>ITB 的 48 页 PDF 整理为 45 张素材：1 张封面、44 张正文图片。火塘的两份 PDF 共 132 页，以成果版为主，补入前期版本独有研究，去掉重复、空白与待完成内容。</p><div className="split-facts"><div><b>38 张主线</b><p>火塘正文优先呈现理解项目所需的分析与成果。</p></div><div><b>11 张补充</b><p>研究细节进入 8 个展开区，让访客选择深入程度。</p></div></div><p>两个项目合计整理出 95 张独立素材，其中包含 2 张封面。这是资料整理规模，不代表 95 个独立设计成果。内容描述仍需得到原材料支持。</p></article>
<article className="decision"><span className="decision-label">02 / 清晰度与资源成本</span><h3>正文轻量阅读，点击后保留细节。</h3><p>所有正文直接使用高清原图会提高资源成本，过度压缩又使建筑图纸难以辨认。统一图片组件使用不同尺寸 WebP、宽高声明、懒加载与异步解码，同时保留点击后的高清原图。</p><Results headers={['默认图片引用文件去重体积','优化前','优化后']} rows={[
['首页作品图','21.21 MiB','0.38 MiB'],['Work 封面','37.19 MiB','0.76 MiB'],['Half Diary','83.58 MiB','2.11 MiB']
]}/><p className="method-note">这是页面默认图片引用的文件体积，不能换算为实际加载速度提升；也不代表所有正文已经动态加载或虚拟化。</p></article>
<article className="decision"><span className="decision-label">03 / 阅读连续性</span><h3>关闭大图后，不能让读者重新找位置。</h3><p>长页面中放大图纸后，关闭操作曾触发剧烈滚动。后续调整焦点与滚动恢复，并检查快速关闭、滚轮冲突和反复导航的监听器清理。</p><div className="decision-result"><b>验收从“能打开”，扩展到“能返回”。</b><p>火塘图纸关闭前后滚动位置均为 14930px；首页 → 项目 → Banner → 关闭 → 首页连续三轮，每轮保持一个图库窗口。这些是具体回归记录，尚非真实用户体验评分。</p></div></article>
<article className="decision"><span className="decision-label">04 / 模型范围与默认镜头</span><h3>转换成功，不等于主体容易理解。</h3><p>火塘原始 SketchUp 场景包含外围研究、拆解和重复模型。第一次全量转换后，主体建筑在总览中过小。网页副本因此选择中央完整项目，默认聚焦院落，并单独提供完整场地视角。</p><Results headers={['模型处理','源文件','网页模型']} rows={[
['ITB · 保留 23 个原图层','约 151.3 MiB','约 6.2 MiB'],['火塘 · 聚焦中央完整项目','约 294.4 MiB','约 22.7 MiB']
]}/><p className="method-note">火塘的减少来自范围筛选、实例复用与资源压缩，不能表述为无损压缩。默认镜头和内容范围同样属于产品决策。</p></article>
<article className="decision"><span className="decision-label">05 / 完整交互生命周期</span><h3>一次打开正常，还不足以通过验收。</h3><p>页面返回后曾出现两个 3D 画布。修正初始化与资源清理后，进行两轮返回 ITB 的回归，每次保持一个画布；关闭为 0，重新打开为 1。查看器离开可视区时暂停绘制，离开页面时释放资源。</p><p>注入 HTTP 503 后，界面提供重试和继续阅读提示。模型失败不应阻止访客阅读其余项目内容。</p></article></section>
<section id="delivery" className="story-section"><p className="eyebrow">04 / DELIVERY & COLLABORATION</p><h2>由我确定目标，<br/><strong>与 AI 协作交付。</strong></h2><p>我提供真实资料，提出目标、需求顺序、内容方向与验收要求，并依据每轮结果继续调整。Claude Code 和 Codex 协助完成具体脚本、模型转换、组件实现与大量检查，部分加载和异常处理方案在开发过程中补充。</p><div className="pipeline"><span>CONTENT / 内容路径</span><ol>{['核对 PDF 来源、署名与版本','提取素材 · 去重 · 主线与补充内容分层','生成响应式展示图 · 保留高清原图','章节导航 · 大图查看 · 退出与返回验证'].map(x=><li key={x}>{x}</li>)}</ol></div><div className="pipeline"><span>3D / 模型路径</span><ol>{['真实 Rhino / SketchUp 模型','导出网页 GLB · 范围筛选与优化','格式校验 · 按需加载 · Three.js 查看器','默认镜头与显示控制 · 关闭、返回及失败回归'].map(x=><li key={x}>{x}</li>)}</ol></div><p className="method-note">本案例讲述的是网站产品开发实践。网站承载的原建筑作品包含 Yuxiang Wang、Han Liu 合作署名，未进一步确认分工前，不将全部建筑设计归为个人独立成果。</p></section>
<section id="evaluation" className="story-section"><p className="eyebrow">05 / EVIDENCE & VALIDATION</p><h2>记录成功，<strong>也记录失败。</strong></h2><p>以下来自项目已有工程与浏览器检查记录。以下保留此前本地回归记录；最新生产访问检查见上方独立证据。工程验收不代表真实用户验证已经完成。</p><Results headers={['验收项','已有记录']} rows={[
['生产构建与图片资源','11 个静态页面；全站本地图片引用检查无缺失'],['高清图纸','火塘首层图纸打开 3200 × 2263 原图'],['图片缩放','Half Diary 显示宽度 1020 → 2768 → 1020px'],['关闭后恢复','Half Diary 约 1667.33px；火塘图纸前后均为 14930px'],['模型格式','两个网页模型及解码展开后的检查均为 0 errors / 0 warnings'],['重复初始化','修复后两轮返回 ITB，每轮一个画布'],['失败路径','ITB 注入 HTTP 503 后出现重试与继续阅读提示'],['火塘交互抽查','旋转、预设视角、缩放、分组隐藏、键盘平移与关闭通过'],['窄屏回归','390 × 844 模拟视口下无横向溢出，按钮可换行'],['共用组件回归','火塘接入后 ITB 仍成功加载']
]}/><h3>本地模型检查，不当作线上性能承诺</h3><Results headers={['本地记录','下载阶段','挂载至第一帧提交']} rows={[
['ITB','94ms','633ms'],['祖母的火塘','117ms','1313ms']
]}/><p className="method-note">以上来自本地开发环境；第一帧提交不等于 GPU 完成绘制或用户已感知可操作。已有访问开启 VPN，也不应标为中国大陆直连测试。</p><div className="insight"><span>FAILURE RECORDS</span><h3>失败帮助我补全验收范围。</h3><p>大图关闭后的页面跳动、返回后重复画布、全量模型主体过小，分别暴露阅读连续性、资源生命周期与展示目标问题。另有 PDF 裁边截断比例尺、模型变换出现 14 个旋转校验错误的记录，可作为内容与转换质量的补充证据。</p></div><a className="text-action" href={repo} target="_blank" rel="noreferrer">查看项目源码仓库 ↗</a><p className="method-note">2026.09.07 已归档并推送网站代码、95 张项目素材与两个 GLB；个人复盘与部分转换资料仍为本地文件。</p></section>
<section id="reflection" className="story-section"><p className="eyebrow">06 / LIMITS & NEXT STEPS</p><h2>先验证体验，<br/><span>再判断 AI 的价值。</span></h2><p>目前网站完成核心内容展示与两个真实模型的交互原型。AI 用于开发协作，尚未接入访客自然语言导览、LLM API 或智能问答，当前不将其描述为已完成的访客端 AI 产品。</p><div className="split-facts"><div><h3>尚未完成的验证</h3><ul><li>iPhone、Android 真机与真实触摸。</li><li>多浏览器矩阵、弱网与持续交互性能。</li><li>足够次数的加载成功率统计。</li><li>3–5 名真实用户任务测试，以及至少两轮真人反馈迭代。</li><li>国内直连、移动网络与跨地区访问验证；已有代理环境生产访问记录。</li></ul></div><div><h3>下一步产品问题</h3><ol><li>持续记录公开入口与版本，并补充不同网络条件下的使用验证。</li><li>观察访客如何找到图纸、理解空间和退出模型。</li><li>记录耗时、误操作、求助与反馈，再决定改进顺序。</li><li>验证自然语言控制是否比现有按钮更有帮助，再确定访客端 AI 功能范围。</li></ol></div></div><div className="closing"><p>这次实践让我把视觉要求转化为可验收的约束：内容有来源，细节能看清，操作能返回，失败有出口。</p><a className="text-action" href="/#projects">← 返回全部作品</a><a className="text-action" href="/projects/knowledge-copilot">阅读 RAG 知识助手案例 ↗</a></div></section>
</div></div></section><EvidencePanel project="spatial"/><div className="wrap case-next"><a href="/#projects">← 返回全部作品</a><a href="/resume/">查看简历 ↗</a><a href="mailto:m17347819733@163.com">邮件交流 ↗</a></div></main><footer className="wrap footer"><span>© 2026 王誉翔 · Yuxiang Wang</span><span>Architecture Portfolio & Interactive 3D</span><a href="#top">回到顶部 ↑</a></footer></div>}
